### ISSUE TITLE
How do I create examples?

### ISSUE THREAD

**Issue by eNzyOfficial** [davidhsianturi/laravel-compass#129]
I can't see anything in the documentation and looking through the code isn't completely clear either. I see there's an `example` column in the database table, but I can't see any way of setting it from within compass. Does this have to be done manually via code? If so can you give an example?

Thanks!

**Comment by davidhsianturi** [comment]
Hey, you can add an 'example request' and 'example response' by clicking the `save response as examples` button via  Compass's UI.
