### ISSUE TITLE
CORS when run another port 80/443

### ISSUE THREAD

**Issue by nguyentranchung** [davidhsianturi/laravel-compass#13]
![image](https://user-images.githubusercontent.com/9611224/67917801-876e2e80-fbdd-11e9-9107-57e727e5d8cb.png)

**Comment by railken** [comment]
CORS should be resolved by the backend

**Comment by nguyentranchung** [comment]
@railken Why is the system running on port 88, and api running on the default port 80? Not logic

**Comment by railken** [comment]
You have to change the url of your application in your `.env`

**Comment by nguyentranchung** [comment]
@railken thanks you! it's working.
