### ISSUE TITLE
migration is not being run on production, only on local

### ISSUE THREAD

**Issue by vesper8** [davidhsianturi/laravel-compass#134]
I'm at a loss to understand why this is the case. I've run the install command and when I run migrations on my dev local environment it runs the compass migration just fine, but on production it refuses to run it... any idea what could be causing this?

**Comment by davidhsianturi** [comment]
@vesper8 are there any error messages? I have no idea, have you ignored the migration? https://davidhsianturi.com/laravel-compass/configuration/#migration-customization

**Comment by vesper8** [comment]
@davidhsianturi No I do not ignore the migrations or get any errors. But upon a closer look now I guess the answer is really quite simple.. your installation instructions suggest that we install this with the `--dev` flag.. so on production this package is simply not installed at all.. hence why the migration doesn't run.. and neither is the package auto-loaded.. because it's just not meant to be installed on production?

Is that still the case? I would have thought that a package such as this would be useful in production as well.. but it's not meant to be?

**Comment by davidhsianturi** [comment]
Yes, Compass is only intended to be used in a local/development environment.
