### ISSUE TITLE
How to write documentation?

### ISSUE THREAD

**Issue by SachinAgarwal1337** [davidhsianturi/laravel-compass#15]
I am not able to figure out how to write the documentation for APIs.
Compass shows url as the list where as I want to give a label to the URL and want to provide the list of Parameters it will be accepting. 
Readme.md is giving much info on how I can achieve it.

**Comment by davidhsianturi** [comment]
On the `about` tab, you can update the ` title` and `description` for the endpoint.
if you want to provide an example for the endpoint, try to send API call and save response as example.

build the documentation with the `compass:build` artisan command:
`php artisan compass:build`

head to `yourproject.test/docs/index.html` to see the documentation.

**Comment by SachinAgarwal1337** [comment]
@davidhsianturi  Thanks. Got it. It's really an amazing package. 
I hope you plan on adding dark theme as well.

Also is there a way I can pass on JSON data in body?

**Comment by SachinAgarwal1337** [comment]
@davidhsianturi  Thanks that really helps

**Comment by davidhsianturi** [comment]
@SachinAgarwal1337  raw request body options is already in PR #39 I need your help to review the result.
yes, dark theme would be good too, feel free to send a PR.
