### ISSUE TITLE
Question: What is the purpose of compass:build?

### ISSUE THREAD

**Issue by railken** [davidhsianturi/laravel-compass#16]
If all requests are retrieved from the [route facade](https://github.com/davidhsianturi/laravel-compass/blob/master/src/Compass.php#L25), what is the purpose of building the docs with `php artisan compass:build`? How should i merge custom descriptions in markdown files with the current routes?

**Comment by Kimleang** [comment]
correct me if I'm wrong, the purpose of `compass:build` is to generate API documentation. After you run this command public/docs will be generated.

**Comment by davidhsianturi** [comment]
Why? what you try to leverage using that method? don't get me wrong, the `compass:build` artisan command only to build/generate the API documentation. 
> How should i merge custom descriptions in markdown files with the current routes?

are you mean you want to modify the description directly in markdown files?  [@todo](https://github.com/davidhsianturi/laravel-compass/blob/6c77ad7e4cd104287609f312ddf3fb163484d9df/src/SlateBuilder.php#L69)

**Comment by railken** [comment]
Ok, i tought they were somehow related, because this page asks you to generate the docs

![img](https://i.imgur.com/2BImJ27.png)

while in reality documentation and api explorer are two separed things, thanks

**Comment by mojtabaahn** [comment]
Came here for same question, I think docs are miss-leading about documentations..
