### ISSUE TITLE
Request domain should be configurable

### ISSUE THREAD

**Issue by sasokovacic** [davidhsianturi/laravel-compass#161]
Hi, the plugin uses APP_URL for making requests. It would be really useful if one could change it using some env variable.
It can use APP_URL by default, but one should be able to overwrite this value.

Right now I have to append a custom domain to each request route manually.

**Comment by davidhsianturi** [comment]
I do not fully understand the question is, but the default base URL is intended to always use APP_URL and you can use a [variabe/sub-domain](https://github.com/davidhsianturi/laravel-compass/pull/162)

I'm closing this issue now, but feel free to continue the discussion here.

**Comment by sasokovacic** [comment]
@davidhsianturi Hi, what I mean is that the domain/subdomain should be configurable. It should not rely on APP_URL. I'm working on a SPA app where a base domain (example.com) is used for a JS app and a subdomain (api.example.com) is used for an API app. The APP_URL in an API is set to the base domain (JS app) and not to the API subdomain because it's used in different areas for URL generation, e.g. forgotten password, activation URL, etc. In this case, your plugin makes requests to the base domain, where the JS app resides but it should be making requests to the API app. So it would be really useful to somehow set a domain/subdomain to which your plugin should send requests.

**Comment by davidhsianturi** [comment]
the domain/sub-domain is configurable, go to the Compas config file in the route section, in your case try to change the prefix to `api` the config looks like this:

```php
'routes' => [
      'domains' => [
          '*',
      ],

      'prefixes' => [
          '*',
      ],

      'exclude' => [
          'compass.*',
          'debugbar.*',
          '_ignition/*',
          'telescope/*',
      ],

    'base_uri' => 'api',
],
```
