### ISSUE TITLE
Can documents add descriptions and variables

### ISSUE THREAD

**Issue by febelery** [davidhsianturi/laravel-compass#18]
## just like this :

![postman](https://i.ibb.co/q7Yvd4S/TIM-20191102155949.png)

**Comment by railken** [comment]
There is a tab called 'About' where you can edit the description, not sure about variables

**Comment by davidhsianturi** [comment]
@febelery  `variables` are not supported (yet). I know it can be very useful especially for providing the API keys. I think we can do it differently by using the Laravel auth to provide the API keys automatically, but in the meantime what you can do is just fill the value manually.
