### ISSUE TITLE
Added new request without edit route/web.php

### ISSUE THREAD

**Issue by JuniYadi** [davidhsianturi/laravel-compass#2]
Halo, terimakasih atas packagenya, sangat bermanfaat.

saya ingin menanyakan, apakah mungkin bisa ditambahkan fitur untuk menambah route tanpa harus edit route/web.php ?

![191005_0013](https://user-images.githubusercontent.com/31454084/66254358-61509c80-e79f-11e9-8d18-e868992e3dcb.png)

karena saya cek setiap request jika di save akan tersimpan ke table `compass_routeables` menggunakan `save request`. jika memungkinkan maka akan sangat membantu untuk pengetesan integrasi apinya atau ditambahkan `save as request` untuk api tambahan langsung ke database.

**Comment by davidhsianturi** [comment]
Halo, semoga membantu ya..
saya rasa tidak, setidaknya untuk saat ini. 
semua daftar request diambil dari Laravel route (internal), tidak untuk menguji endpoint external.

ps: request tidak harus di save ke database, itu opsional. response nya saja yg butuh di save, untuk keperluan membuat dokumentasi API.
