### ISSUE TITLE
"various auth mechanisms" ? 

### ISSUE THREAD

**Issue by vesper8** [davidhsianturi/laravel-compass#20]
Hi there!

Very exciting project with great potential to be useful. I am also very pleasantly surprised that it detected all my routes even though I make use of route annotations and my web.php route file is basically empty (https://github.com/LaravelCollective/annotations) .. awesome! I was sure that this would require additional workaround but nope, it got them all!

I really hope you are going to add more documentation.. your Readme mentions `various auth mechanisms` but this is the only mention of it and nowhere in the issues, or the config, does it seem to mention how to deal with routes that require authentication

In my case, since my Laravel installation is strictly a Rest API, all my authenticated routes make use of a auth:api middleware powered by https://github.com/tymondesigns/jwt-auth

How would I go about mocking this auth so I can test the api calls using Compass?

Also.. a request please.. can you please add a filter search box in the sidebar? I have hundreds of routes and it's quite difficult to locate the route I want to test without using a search

Thank you for making this! Looking forward to developments!

**Comment by davidhsianturi** [comment]
Hi!
Cool, routing in Laravel is awesome!

I'm sorry for the confusion caused, I was made that word seems like "compass handles the auth and providing your API keys automatically" but what I mean is "You can use various auth mechanisms (jwt, oauth, basic key, etc)" Compass will support it as long is organized around REST. 

see #18  let me know if that's what you mean.

Yeah, got it. request accepted 👍

**Comment by vesper8** [comment]
My api endpoints all require jwt token from my client side to allow access. I think what would be the best way to make those api endpoints testable in Laravel Compass is to create an optional middleware that would authenticate the user first and provide the access token automagically

I am not sure how to accomplish this.. but I think it would be a very useful addition to Laravel Compass.. if I could simply check a "checkbox" that says "mock authentication" and it would activate the middleware, generate the token and make it available to Laravel Compass so that it would be automatically provided and the auth-only endpoint would then be accessible

Am I making sense?

**Comment by eNzyOfficial** [comment]
You could possibly look at doing something similar to insomnia client, this would cover a lot more than just auth, eg.

https://support.insomnia.rest/article/43-chaining-requests

**Comment by vesper8** [comment]
this looks really good @eNzyOfficial, what do you think @davidhsianturi? can you add this functionality to Laravel Compass?

**Comment by enzotaufan** [comment]
come on @davidhsianturi you can add the functionality requested by @vesper8 that would be awesome

**Comment by davidhsianturi** [comment]
@vesper8 I'll give a shot this weekend to implement the basic [API auth](https://laravel.com/docs/5.8/api-authentication) first and then we'll see how to support with jwt. I'll keep you update.



> You could possibly look at doing something similar to insomnia client, this would cover a lot more than just auth, eg.
> 
> https://support.insomnia.rest/article/43-chaining-requests

thanks for sharing this, worth to read!


> come on @davidhsianturi you can add the functionality requested by @vesper8 that would be awesome

😂
