### ISSUE TITLE
Funny looking page

### ISSUE THREAD

**Issue by cacpmw** [davidhsianturi/laravel-compass#22]
Here is what I did:

1. `composer require davidhsianturi/laravel-compass --dev`
1. `php artisan compass:install`
1. `php artisan migrate`
1. `php artisan compass:publish`
1. `php artisan compass:build`
1. `localhost/docs/index.html`

Then I got this funny looking page:

![image](https://user-images.githubusercontent.com/7819913/68093628-6411e080-fe76-11e9-80e6-db80f6026096.png)

Also how do I edit endpoint's information with examples and stuff?

**Comment by davidhsianturi** [comment]
Hey, that page looks good, it means Compass has successfully built the API documentation for you and btw please read the [readme](https://github.com/davidhsianturi/laravel-compass#configuration) file carefully.

> Also how do I edit endpoint's information with examples and stuff?

head to `yourproject.test/compass`
