### ISSUE TITLE
Request: add JSON option to request body instead of fields

### ISSUE THREAD

**Issue by cinco-de-mauro** [davidhsianturi/laravel-compass#30]
I mostly write APIs that accept JSON. Which can get a little more complex than simple key value pairs. 

I would like an option, on the request body, to paste in raw JSON data, instead of the key value form fields.

Let me know if there's a better place to post requests.

Thanks for this package BTW!

**Comment by akbarcandra** [comment]
Hi @cinco-de-mauro @davidhsianturi
I tried to add this #39 feature, hopefully that feature is working & meet the requirements you need. Feel free to test and review the code, thanks
