### ISSUE TITLE
In my installation it does not look like how it shows in git repo?

### ISSUE THREAD

**Issue by web-nirav** [davidhsianturi/laravel-compass#34]
![demo api page](https://user-images.githubusercontent.com/8157812/68195868-ad307480-ffdd-11e9-9641-946051ec379d.png)

Please let me know why it looks like this and how it should work like shows in git repo

**Comment by akbarcandra** [comment]
I think this issue same as #22 
Have you try to access `yourproject.test/compass` ?

**Comment by davidhsianturi** [comment]
@web-nirav head to `yourproject.test/compass`
