### ISSUE TITLE
Why not use laravel-apidoc-generator?

### ISSUE THREAD

**Issue by zek** [davidhsianturi/laravel-compass#37]
I really liked the interface of compass. I wonder why don't you use laravel-apidoc-generator to generate docs. 

Right now I really don't know which annotations I should use to document the API.

I believe apidoc-generator + compass would be awesome.

**Comment by fntneves** [comment]
I don't know where to find docs for using this package. Don't know what annotations are used, how to organize groups os endpoints, etc.

Are you using something?

/cc @davidhsianturi

**Comment by davidhsianturi** [comment]
Compass takes a different approach to build the API docs. 
if you want to document your API from your code using mainly annotations (in doc block comments), you can install [laravel-apidoc-generator](https://github.com/mpociot/laravel-apidoc-generator). with Compass, you only documenting through the UI [#15](https://github.com/davidhsianturi/laravel-compass/issues/15#issuecomment-548796789).

**Comment by fntneves** [comment]
And how do you create groups in UI? Is it possible?

**Comment by davidhsianturi** [comment]
Compass group the routes based on how you organized the routes in your project.
see the configuration: https://github.com/davidhsianturi/laravel-compass#configuration

for example:
`api/v1/products/`
`api/v1/products/{product}`

Compass will group these routes to `Api`
if you want Compass grouping the routes to `Products`. change the `base_uri` in routes configuration like this `'base_uri' => 'api/v1'`

This implementation will force us to build an API is organized around [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer),  has predictable resource-oriented URLs, and I think is quite useful.
