### ISSUE TITLE
Release documentation

### ISSUE THREAD

**Issue by akbarcandra** [davidhsianturi/laravel-compass#38]
Hi @davidhsianturi,

I was wondering about the short release documentation. For well-maintained documentation, isn't it better to write more description on every release (what things are added, changed, fixed, or removed)? Just like what Laravel did on each release. I think that will be more helpful for the developers who are using this package. I myself find it hard to find the changes on the latest release.

Would you mind adding more information to each release?

**Comment by davidhsianturi** [comment]
absolutely, how about to keep a changelog? https://keepachangelog.com/en/1.0.0/

**Comment by akbarcandra** [comment]
Ya sure, that will be great
