### ISSUE TITLE
Request body key type dropdown broken in Firefox

### ISSUE THREAD

**Issue by erikgaal** [davidhsianturi/laravel-compass#44]
Hi there,

It seems you cannot switch between `Text` and `File` type on the request body on Firefox. The dropdown immediately closes and I'm unable to select another option. I've attached a GIF that demonstrates the issue.

I've tested this on Firefox 70, where it fails and on Chrome 79, where it works just fine. I'm running Compass v0.2.0.

![ezgif-5-2c1e1139a5b8](https://user-images.githubusercontent.com/1234268/69157429-2f905c80-0ae5-11ea-9bcd-09ee4164236c.gif)

**Comment by erikgaal** [comment]
Awesome! Thanks @davidhsianturi 😄

**Comment by davidhsianturi** [comment]
Long shot! thanks for reporting, btw 👍
