### ISSUE TITLE
GET with body

### ISSUE THREAD

**Issue by snezhkoigor** [davidhsianturi/laravel-compass#45]
Hi. I think that there some bug.

Browser console show me that no data sending when I trying to send some data to GET-endpoint with raw json data.

<img width="1440" alt="Снимок экрана 2019-11-25 в 18 55 03" src="https://user-images.githubusercontent.com/20436473/69556028-2277df80-0fb5-11ea-8799-b01e6ef5aacb.png">

**Comment by davidhsianturi** [comment]
Hi,
'data' in request body only applicable for request methods `PUT`, `POST`, and `PATCH` at this time.
in your case, it'll works if you use URL parameters instead.

**Comment by snezhkoigor** [comment]
Will you add this feature for GET requests?

**Comment by railken** [comment]
> The RFC2616 referenced as "HTTP/1.1 spec" is now obsolete. In 2014 it was replaced by RFCs 7230-7237. Quote "the message-body SHOULD be ignored when handling the request" has been deleted. It's now just "Request message framing is independent of method semantics, even if the method doesn't define any use for a message body" The 2nd quote "The GET method means retrieve whatever information ... is identified by the Request-URI" was deleted. - From a comment

[Source](https://stackoverflow.com/questions/978061/http-get-with-request-body)

**Comment by davidhsianturi** [comment]
> Will you add this feature for GET requests?

No plans to add this at the moment.
