### ISSUE TITLE
Save headers between routes

### ISSUE THREAD

**Issue by emargareten** [davidhsianturi/laravel-compass#50]
Hi, i was wondering if it's possible to save headers between all routes, (or even in some file)

**Comment by davidhsianturi** [comment]
Hello, it's not possible at this time. I'm not sure is there the benefits to `save headers between all routes` 
I'm closing this issue now, but feel free to continue the discussion here.

**Comment by railken** [comment]
Global headers can be actually really useful, or headers based on the group/subgroup. The best example i can think of it is the Authentication token
