### ISSUE TITLE
Header 'origin' not being sent

### ISSUE THREAD

**Issue by emargareten** [davidhsianturi/laravel-compass#51]

**Comment by davidhsianturi** [comment]
is this a bug? can you please explain in more detail?

**Comment by emargareten** [comment]
I have a multi tenant application and am determining which tenant is making the call to backend through the origin header, I then set some objects accordingly.
I was trying to do this through compass by adding the origin header but those objects were not set.
I also noticed in dev tools that it wasn't set.

**Comment by davidhsianturi** [comment]
I see.. are you adds CORS headers support in your Laravel app?
`Origin` is a forbidden header, you would need to configure the backend/server to allows CORS requests.

**Comment by emargareten** [comment]
I do allow CORS for this case (subdomain), it just doesn't send the header at all, it might be the browser that blocks it but there should be a workaround.

**Comment by davidhsianturi** [comment]
Okay, using sub-domain routing is not supported yet #31 
I'll working on it this weekend. so I think in your case, Compass can be accessed from the sub-domain and get the `Origin` request header from the API call.

Access Compass.
`http://tenant1.yourdomain.test/compass`

Make an API call.
```
Request URL: http://yourdomain.test/some-resource
Request Method: GET
```

Expected request header.
```
Host: yourdomain.test
Origin: http://tenant1.yourdomain.test
```

and we don't need to set the `Origin` header. 
I think the forbidden header name will be removed from the suggestion list for the next release.

**Comment by emargareten** [comment]
isn't it possible to allow `origin` header, the same way postman does it?

**Comment by davidhsianturi** [comment]
I don't think so, we access Compass using a browser and we not allowed to modify the forbidden header name. https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

do you have any suggestions?

**Comment by emargareten** [comment]
You are right, postmans chrome app needed [Postman Interceptor](https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo) chrome extension to send forbidden headers.
