### ISSUE TITLE
How to pass authorization token?

### ISSUE THREAD

**Issue by saeedvaziry** [davidhsianturi/laravel-compass#54]
Header values do not support Bearer token

**Comment by saeedvaziry** [comment]
Also, the 401 Error code is not supported.

Unknown Response Code

**Comment by davidhsianturi** [comment]
Hi, the auth header with bearer token and response codes work for me. are there any error messages on the dev console?

**Comment by saeedvaziry** [comment]
My bad. I didn't know that I should set APP_URL in my env.
