### ISSUE TITLE
Excluding routes without route name

### ISSUE THREAD

**Issue by eNzyOfficial** [davidhsianturi/laravel-compass#6]
It seems compass picks up some of the ignition routes and telescope routes due to them not having route names, from what I can tell it's not possible to filter them out using `exclude` in the config. It's not a big deal, but thought it might be worth pointing out, maybe switch from route names to segment matching? eg. `/telescope/*` or `/_ignition/*`.

Anyway, really nice package, keep up the good work!

**Comment by railken** [comment]
Variant 2 is better because in future there might be other types

**Comment by KeironLowe** [comment]
You can remove the ignition routes by adding `_ignition/*` to exclude, but I can't seem to get it to work for Telescope.
