### ISSUE TITLE
quality of life improvements

### ISSUE THREAD

**Issue by vesper8** [davidhsianturi/laravel-compass#61]
I'm glad to see this project is receiving ongoing development.

I just updated to 0.5.0 and here are some things I noticed.

First, I really appreciate the new Auth Tabs.. they are very useful since I use JWT auth for my endpoints so it was quite easy to create a new console command that outputs the JWT token that I can then plug into the auth tab in Compass. I appreciate that this can be saved too. I guess it would be even nicer if this process could be even more automated, for example I could type `jwt:22` and add a custom method somewhere call `compass_auth_jwt($userId)` and this method would accept the userId (22) in this case and return the token. This would be good to avoid having to manually generate the token every time, especially in the case of rapidly expiring tokens

Another thing that is badly missing, and I see this has not only been requested but someone even submitted a PR, is the ability to specify a middleware or gate. This should be a pretty easy thing to add, plus someone's already done the ground work (or all of the work). Not everyone wants to use this only in a dev/local environment. This is a minor change that adds much needed security and flexibility in how we use this package.

Another thing, I just updated to 0.5 and I republished all the assets, but I noticed that the Compass dashboard still says `0.4.1`. Not sure if you forgot to update the version or if the republishing of the assets somehow failed?

Two quality of life improvements I would really like to see is a) add a little search filter in the left column to filter by string. I have over 200 endpoints and it's quite difficult to manage.

Secondly, let us create our own groups. I like that you auto-create groups based on url, but I don't fully agree with how that works and would like to be able to create my own custom groups. It would also be nice to be able to reorder these groups. There are many groups that I don't want to hide completely but are of much less importance and will rarely be tested so I'd rather have those at the bottom. As an example of what I'm describing, I have over 100 endpoints that all start with `/api` and so you've created a group for `Api` and then nothing is grouped under there. I would create multiple sub-groups, or top level groups for those endpoints.. those are the main endpoints I want to test.

**Comment by vesper8** [comment]
I can see that https://github.com/davidhsianturi/laravel-compass/blob/master/public/app.js still has the string "Laravel Compass v0.4.1"

**Comment by davidhsianturi** [comment]
> ... ... ...
>  I guess it would be even nicer if this process could be even more automated, for example I could type jwt:22 and add a custom method somewhere call compass_auth_jwt($userId) and this method would accept the userId (22) in this case and return the token. This would be good to avoid having to manually generate the token every time, especially in the case of rapidly expiring tokens

@vesper8  Thanks for the details. you made a good point here, the ability to automatically provide a token is would very helpful. btw I'm working on it, checkout to authenticator branch, so far only support [token driver](https://laravel.com/docs/5.8/api-authentication) but you will get the idea.

> Another thing that is badly missing, and I see this has not only been requested but someone even submitted a PR, is the ability to specify a middleware or gate.
> ... ... ...

 I just don't see the benefit of that or I do not fully understand the needs, so what the case made you want to configure Compass run in production?

> Another thing, I just updated to 0.5 and I republished all the assets, but I noticed that the Compass dashboard still says 0.4.1. Not sure if you forgot to update the version or if the republishing of the assets somehow failed?

good catch! it was not intended to show the version, just a simple welcome text. so stupid forgot to change that, will release a quick fix today. thanks!

> Secondly, let us create our own groups. I like that you auto-create groups based on url, but I don't fully agree with how that works and would like to be able to create my own custom groups. It would also be nice to be able to reorder these groups. There are many groups that I don't want to hide completely but are of much less importance and will rarely be tested so I'd rather have those at the bottom. As an example of what I'm describing, I have over 100 endpoints that all start with `/api` and so you've created a group for `Api` and then nothing is grouped under there. I would create multiple sub-groups, or top level groups for those endpoints.. those are the main endpoints I want to test.

Compass grouping the endpoints based on how you organized the routes. so make sure to organize your routes around [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer). that's it, easy and simple. anyway there is a case we have a prefix on each resource, in your case is `api` Compass can ignore this prefix, so make sure to update `base_uri` value in to `api` in Compass configuration file, also easy and simple. in practice, there are no configurable custom groups needed. if you want all endpoints are grouped under a prefix, use `*` as a wildcard to match any character.

**Comment by davidhsianturi** [comment]
Hey, @vesper8 v1.0.0 has been tagged, please see [CHANGELOG](CHANGELOG.md) for more information what has changed recently. 
I'm closing this issue now, but feel free to continue the discussion here.
