### ISSUE TITLE
requirements conflict with mnapoli/front-yaml ^1.5 & symfony/yaml ^5.0

### ISSUE THREAD

**Issue by olivM** [davidhsianturi/laravel-compass#80]
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/routing (locked at v5.0.7) -> satisfiable by symfony/routing[v5.0.7].
    - Installation request for symfony/yaml (locked at v5.0.7) -> satisfiable by symfony/yaml[v5.0.7].
    - davidhsianturi/laravel-compass 1.x-dev requires mpociot/documentarian ^0.4.0 -> satisfiable by mpociot/documentarian[0.4.0].
    - davidhsianturi/laravel-compass v1.0.0 requires mpociot/documentarian ^0.4.0 -> satisfiable by mpociot/documentarian[0.4.0].
    - Conclusion: don't install mpociot/documentarian 0.4.0
    - Installation request for davidhsianturi/laravel-compass ^1.0 -> satisfiable by davidhsianturi/laravel-compass[1.x-dev, v1.0.0].
`

**Comment by davidhsianturi** [comment]
hey @olivM I can't replicate your issue, the installation working fine for me on Laravel 6 and 7.

**Comment by olivM** [comment]
me neither :)
i reinstalled the project ( with the same composer.json )
and everything worked fine

strange :/
