### ISSUE TITLE
Send Button not working for any API

### ISSUE THREAD

**Issue by kinnngg** [davidhsianturi/laravel-compass#81]
Hi,
    Is there any issue with Laravel 7? Send button is not working for my projects. They are not even sending any requests, I checked in the Network tab.

https://i.imgur.com/KaFQJJJ.gif

**Comment by davidhsianturi** [comment]
hey @kinnngg I can't replicate your issue, the send button working fine for me on Laravel 7, just make sure your browser extension is not blocking the request.

**Comment by kinnngg** [comment]
Fixed. I didn't had `http://` in my APP_URL env variable. Due to that button was not firing. 
Thanks.
