### ISSUE TITLE
There is data but not displayed

### ISSUE THREAD

**Issue by nguyentranchung** [davidhsianturi/laravel-compass#9]
![image](https://user-images.githubusercontent.com/9611224/67825637-51fa1000-fb0d-11e9-90e8-95b51c6f932b.png)

**Comment by nguyentranchung** [comment]
What did I do wrong?

**Comment by jinoantony** [comment]
Same issue here. Ajax call is picking up data correctly, but nothing is displayed.

**Comment by antonkomarev** [comment]
It might be related to #7

**Comment by davidhsianturi** [comment]
@nguyentranchung @jinoantony if you guys have a route that redirects to another URI, the bug has been fixed and merged to the master branch #7

**Comment by nguyentranchung** [comment]
@davidhsianturi There is no redirect here.
laravel-compass\resources\js\components\SidebarMenu.vue i found problem

```vue
<div :class="{'hidden': !isOpen, 'block': isOpen}" class="md:block md:h-full md:flex md:flex-col">
```
![image](https://user-images.githubusercontent.com/9611224/67917270-dc10aa00-fbdb-11e9-8235-297e5bac598c.png)

```js
    data() {
        return {
            requests: [],
            ready: false,
            isOpen: false,
            currentTab: 'list',
        }
    },
```
isOpen -> false?

**Comment by davidhsianturi** [comment]
@nguyentranchung it's weird, the 'hidden' class name is working for me. the sidebar only disappears on the small screen, is the request list appear when you remove the 'hidden' class? (try to resize your browser)

**Comment by nguyentranchung** [comment]
A few extensions on chrome did that.
