### ISSUE TITLE
laravel 8 can't install

### ISSUE THREAD

**Issue by Lowellddh** [davidhsianturi/laravel-compass#97]
Problem 1
    - Installation request for davidhsianturi/laravel-compass ^1.0 -> satisfiable by davidhsianturi/laravel-compass[1.x-dev, v1.0.0, v1.0.1].
    - Conclusion: don't install laravel/framework v8.0.4
    - Installation request for laravel/framework (locked at v8.0.3, required as ^8.0) -> satisfiable by laravel/framework[v8.0.3].
    - Conclusion: install mpociot/documentarian 0.4.0
    - Can only install one of: laravel/framework[8.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.2, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.3, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.0.3].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.0.3].
    - Conclusion: don't install mpociot/documentarian 0.4.0|install laravel/framework 5.7.x-dev
    - Installation request for laravel/framework ^8.0 -> satisfiable by laravel/framework[8.x-dev, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4].

**Comment by davidhsianturi** [comment]
not supported yet, we are waiting for some dependency updates to support Laravel 8.x first.

**Comment by Lowellddh** [comment]
> not supported yet, we are waiting for some dependency updates to support Laravel 8.x first.

OK，thank you

**Comment by davidhsianturi** [comment]
@Lowellddh now you can try [v1.1.0](https://github.com/davidhsianturi/laravel-compass/releases/tag/v1.1.0) for Laravel 8.x
